"""Tests for pg_diff_cli.formatter."""

from __future__ import annotations

import pytest

from pg_diff_cli.formatter import (
    FormatOptions,
    OutputFormat,
    _classify,
    _redact,
    format_sql,
)


def test_format_sql_empty_returns_no_changes_comment():
    result = format_sql([], FormatOptions())
    assert "No schema changes" in result


def test_format_sql_plain_single_statement():
    stmts = ["ALTER TABLE foo ADD COLUMN bar INT"]
    result = format_sql(stmts, FormatOptions(include_header=False))
    assert "ALTER TABLE foo ADD COLUMN bar INT;" in result
    assert "--" not in result


def test_format_sql_annotated_adds_label():
    stmts = ["ALTER TABLE foo ADD COLUMN bar INT"]
    opts = FormatOptions(fmt=OutputFormat.ANNOTATED, include_header=False)
    result = format_sql(stmts, opts)
    assert "-- add column" in result
    assert "ALTER TABLE foo ADD COLUMN bar INT;" in result


def test_format_sql_dry_run_no_semicolons():
    stmts = ["CREATE TABLE t (id INT)", "DROP TABLE old"]
    opts = FormatOptions(fmt=OutputFormat.DRY_RUN, include_header=False)
    result = format_sql(stmts, opts)
    assert "DRY RUN: 2 statement(s)" in result
    assert ";" not in result


def test_format_sql_includes_header_when_dsns_provided():
    stmts = ["DROP TABLE legacy"]
    opts = FormatOptions(include_header=True)
    result = format_sql(stmts, opts, source_dsn="postgresql://user:pw@host/db", target_dsn="postgresql://user:pw@host/db2")
    assert "-- Migration generated by pg-diff-cli" in result
    assert "***" in result  # password redacted


def test_format_sql_no_header_when_flag_false():
    stmts = ["DROP TABLE t"]
    opts = FormatOptions(include_header=False)
    result = format_sql(stmts, opts, source_dsn="postgresql://a:b@h/db")
    assert "Migration generated" not in result


def test_redact_removes_password():
    dsn = "postgresql://alice:secret@localhost/mydb"
    assert "secret" not in _redact(dsn)
    assert "***" in _redact(dsn)
    assert "alice" in _redact(dsn)


def test_redact_no_password_unchanged():
    dsn = "postgresql://localhost/mydb"
    assert _redact(dsn) == dsn


@pytest.mark.parametrize(
    "stmt,expected",
    [
        ("ALTER TABLE t ADD COLUMN c INT", "add column"),
        ("ALTER TABLE t DROP COLUMN c", "drop column"),
        ("ALTER TABLE t ALTER COLUMN c TYPE TEXT", "alter column"),
        ("CREATE TABLE new_t (id INT)", "create table"),
        ("DROP TABLE old_t", "drop table"),
        ("VACUUM FULL", "statement"),
    ],
)
def test_classify_labels(stmt, expected):
    assert _classify(stmt) == expected
