"""Output formatters for migration SQL (plain text, annotated, dry-run summary)."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List

from pg_diff_cli.schema_differ import SchemaDiff


class OutputFormat(str, Enum):
    PLAIN = "plain"
    ANNOTATED = "annotated"
    DRY_RUN = "dry-run"


@dataclass
class FormatOptions:
    fmt: OutputFormat = OutputFormat.PLAIN
    include_header: bool = True
    separator: str = ";"
    extra_tags: List[str] = field(default_factory=list)


def _header_comment(source_dsn: str, target_dsn: str) -> str:
    """Return a SQL block comment header identifying the migration origin."""
    src = _redact(source_dsn)
    tgt = _redact(target_dsn)
    return f"-- Migration generated by pg-diff-cli\n-- source: {src}\n-- target: {tgt}\n"


def _redact(dsn: str) -> str:
    """Strip password from a DSN string for safe display."""
    import re
    return re.sub(r"(:)[^:@]+(@)", r"\1***\2", dsn)


def format_sql(
    statements: List[str],
    options: FormatOptions,
    source_dsn: str = "",
    target_dsn: str = "",
) -> str:
    """Render a list of SQL statements according to *options*."""
    if not statements:
        return "-- No schema changes detected.\n"

    parts: List[str] = []

    if options.include_header and (source_dsn or target_dsn):
        parts.append(_header_comment(source_dsn, target_dsn))

    if options.fmt == OutputFormat.DRY_RUN:
        parts.append(f"-- DRY RUN: {len(statements)} statement(s) would be applied\n")
        for i, stmt in enumerate(statements, 1):
            parts.append(f"-- [{i}] {stmt.strip()}")
        return "\n".join(parts) + "\n"

    for stmt in statements:
        clean = stmt.strip().rstrip(";")
        if options.fmt == OutputFormat.ANNOTATED:
            kind = _classify(clean)
            parts.append(f"-- {kind}")
        parts.append(clean + options.separator)

    return "\n".join(parts) + "\n"


def _classify(stmt: str) -> str:
    """Return a short human-readable label for a SQL statement."""
    upper = stmt.upper().lstrip()
    if upper.startswith("ALTER TABLE") and "ADD COLUMN" in upper:
        return "add column"
    if upper.startswith("ALTER TABLE") and "DROP COLUMN" in upper:
        return "drop column"
    if upper.startswith("ALTER TABLE") and "ALTER COLUMN" in upper:
        return "alter column"
    if upper.startswith("CREATE TABLE"):
        return "create table"
    if upper.startswith("DROP TABLE"):
        return "drop table"
    return "statement"
